from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple, Union

from flask import Blueprint, current_app, jsonify, request
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.security import check_password_hash, generate_password_hash

from ...models.user import User
from ..database import db_session
from ..security import require_auth

def register() -> Union[Dict[str, Any], Tuple[Dict[str, Any], int]]: ...
def login() -> Union[Dict[str, Any], Tuple[Dict[str, Any], int]]: ...
def logout() -> Dict[str, str]: ...
def get_current_user() -> Dict[str, Any]: ...
def update_profile() -> Union[Dict[str, Any], Tuple[Dict[str, Any], int]]: ...
def unauthorized(error: ...): ...
