from functools import wraps
from typing import Any, Callable, Dict, Optional, TypeVar, cast

from flask import Response, current_app, jsonify, request
from werkzeug.wrappers import Response as WerkzeugResponse

from .service import AuthenticationService

def login_required(f: ...): ...
def admin_required(f: ...): ...
def session_required(f: ...): ...
def rate_limit(limit: ...): ...
def require_2fa(f: ...): ...
