from typing import Any, Dict, List, Optional, Tuple, Union

from flask import Request, Response, current_app, g, jsonify, request
from flask.typing import ResponseReturnValue
from werkzeug.wrappers import Response as WerkzeugResponse

from .exceptions import AuthenticationError, SessionError, TokenError

def auth_middleware(app: ...): ...
def session_middleware(app: ...): ...
def rate_limit_middleware(app: ...): ...
def cors_middleware(app: ...): ...
def error_middleware(app: ...): ...
def security_headers_middleware(app: ...): ...
def init_middleware(app: ...): ...
