version: 2
updates:
  # Enable version updates for yarn in the root directory
  - package-ecosystem: 'npm' # Use "npm" for yarn v2+
    directory: '/'
    schedule:
      interval: 'daily'
    # Group updates to reduce noise
    groups:
      # Group all patch and minor updates for dev dependencies
      dev-dependencies:
        dependency-type: 'development'
        update-types:
          - 'patch'
          - 'minor'
      # Group all production dependency updates
      prod-dependencies:
        dependency-type: 'production'
        update-types:
          - 'patch'
          - 'minor'
