version: 2
snapshot:
  widths:
    - 375
    - 768
    - 1280
    - 1920
  minHeight: 1024
  percyCSS: |
    /* Hide dynamic content that changes between snapshots */
    .timestamp { visibility: hidden; }
    .user-avatar { visibility: hidden; }
  enableJavaScript: true
  waitForTimeout: 5000
discovery:
  allowedHostnames: []
  disallowedHostnames: []
  networkIdleTimeout: 100
upload:
  files: 'cypress/screenshots/**/*.png'
  stripStyles: false
