cacheFolder: ./.yarn/cache

enableNetwork: false

enableGlobalCache: false

supportedArchitectures:
  cpu:
    - x64
  os:
    - linux
    - win32
    - darwin
  libc:
    - musl
    - glibc

httpTimeout: 1000000

yarnPath: .yarn/releases/yarn-4.9.3.cjs

pnpMode: loose
nodeLinker: node-modules
