context_automation:
  check_frequency: commit
  enabled: true
  notify_changes: true
  update_tracking: true
  validate_docs: true
documentation:
  index_file: docs/DOCUMENTATION_INDEX.md
  tracking_file: docs/DEVELOPMENT_TRACKING.md
  update_threshold: 10
notifications:
  console: true
  email: false
  log_file: true
