version: '3.8'

services:
  # DojoPool API with Physics Engine
  dojopool-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - PHYSICS_ENGINE_ENABLED=true
      - PHYSICS_ADDON_PATH=/app/addons
    volumes:
      - ./api:/app/api
      - ./src/addon:/app/src/addon
      - ./build:/app/build
    depends_on:
      - redis
      - mongodb
    networks:
      - dojopool-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001/api/physics/health']
      interval: 30s
      timeout: 10s
      retries: 3

  # DojoPool Frontend
  dojopool-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NEXT_PUBLIC_PHYSICS_ENABLED=true
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    depends_on:
      - dojopool-api
    networks:
      - dojopool-network

  # C++ Physics Engine Builder
  physics-builder:
    build:
      context: .
      dockerfile: Dockerfile.physics
    volumes:
      - ./src:/workspace/src
      - ./build:/workspace/build
      - ./cmake:/workspace/cmake
    working_dir: /workspace
    command: >
      bash -c "
        mkdir -p build &&
        cd build &&
        cmake .. -DCMAKE_BUILD_TYPE=Release &&
        make -j$(nproc) &&
        make install_nodejs_addon
      "
    networks:
      - dojopool-network

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - dojopool-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3

  # MongoDB for data persistence
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: dojopool
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - dojopool-network
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Physics Engine Test Service
  physics-tester:
    build:
      context: .
      dockerfile: Dockerfile.tester
    volumes:
      - ./tests:/workspace/tests
      - ./api/src:/workspace/api/src
      - ./build:/workspace/build
    working_dir: /workspace
    command: >
      bash -c "
        python -m pytest tests/integration/test_physics_integration.py -v --tb=short
      "
    depends_on:
      - dojopool-api
      - physics-builder
    networks:
      - dojopool-network
    profiles:
      - testing

volumes:
  redis_data:
  mongodb_data:
  mongodb_config:

networks:
  dojopool-network:
    driver: bridge
