version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=src.dojopool.app
      - FLASK_ENV=production
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - GUNICORN_CMD_ARGS=--bind=0.0.0.0:5000 --workers=4 --timeout=120 --log-level=debug --error-logfile=- --access-logfile=-
      # Google OAuth settings
      - GOOGLE_CLIENT_ID=1234567890-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=GOCSPX-abcdefghijklmnopqrstuvwxyz
      - GOOGLE_MAPS_API_KEY=AIzaSyABCDEFGHIJKLMNOPQRSTUVWXYZabcdefg
      # Session settings
      - SECRET_KEY=your-super-secret-key-change-this-in-production
    ports:
      - "8080:5000"
    volumes:
      - .:/app
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
