version: '3.8'

services:
  # Database service
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dojopool
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dojopool"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis service
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Development API container
  api-dev:
    image: node:20-alpine
    container_name: dojopool-api-dev
    command: tail -f /dev/null # Keeps the container running
    working_dir: /app
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/dojopool
      - PORT=3002
      - NODE_ENV=development
      - CORS_ORIGINS=http://localhost:3000
      - FRONTEND_URL=http://localhost:3000
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_secure_jwt_secret_here
      - SESSION_SECRET=your_secure_session_secret_here
    volumes:
      - .:/app # Mounts your entire project directory into /app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1

  # Development Web container
  web-dev:
    image: node:20-alpine
    container_name: dojopool-web-dev
    command: tail -f /dev/null # Keeps the container running
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3002/api/v1
      - NEXT_PUBLIC_WEBSOCKET_URL=http://localhost:3002
      - NODE_ENV=development
    volumes:
      - .:/app # Mounts your entire project directory into /app
    depends_on:
      - api-dev
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1

volumes:
  postgres_data:
  redis_data:
