from typing import Any, Dict, List, Optional, Union

from flask import Blueprint, current_app, jsonify, request
from flask.typing import ResponseReturnValue
from werkzeug.wrappers import Response

from ..auth.decorators import require_auth
from ..exceptions import PaymentError
from ..models import Transaction, User
from .service import payment_service

def get_payment_methods() -> ResponseReturnValue: ...
def add_payment_method() -> ResponseReturnValue: ...
def remove_payment_method(method_id: ...): ...
def create_payment_intent() -> ResponseReturnValue: ...
def confirm_payment() -> ResponseReturnValue: ...
def webhook() -> ResponseReturnValue: ...
