import os
import re
from typing import Set
from unicodedata import normalize

def sanitize_filename(filename: ...): ...
def is_safe_path(base_path: ...): ...
def get_safe_filename(filename: ...): ...
def is_safe_file_type(filename: ...): ...
