from datetime import datetime, timedelta
from typing import Any, Dict, Optional, Union

import jwt
from flask import current_app

from ..exceptions import TokenError

def verify_token(token: ...): ...
def generate_confirmation_token(user_id: ...): ...
def verify_confirmation_token(token: ...): ...
def generate_reset_token(user_id: ...): ...
def verify_reset_token(token: ...): ...
