apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://dojopool-elasticsearch:9200
    editable: true
    jsonData:
      indexName: dojopool
      timeField: '@timestamp'
      interval: Daily
      logMessageField: message
      logLevelField: level

  - name: PostgreSQL
    type: postgres
    url: dojopool-postgresql:5432
    database: dojopool
    user: dojo_user
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
