"""CLI interface type hints for DojoPool."""

from typing import Any, Callable, Optional

import click
from flask.cli import with_appcontext
from src.core.database.init_db import init_db
from src.core.database.migrations import run_migrations

def init_db_command() -> None: ...
def run_migrations_command() -> None: ...
def register_commands(app: Any) -> None: ...
def create_cli_app() -> click.Group: ...
def get_app_context() -> Any: ...
def run_command(command: Callable[[], None]) -> Callable[[], None]: ...
def create_admin_command(
    email: str,
    password: str,
    first_name: Optional[str] = None,
    last_name: Optional[str] = None,
) -> None: ...
def create_venue_command(
    name: str, address: str, city: str, state: str, country: str, postal_code: str
) -> None: ...
def setup_development_command() -> None: ...
def cleanup_command() -> None: ...
