groups:
- name: backup_alerts
  rules:
  - alert: BackupFailure
    expr: backup_last_status == 0
    for: 1h
    labels:
      severity: critical
    annotations:
      summary: "Backup operation failed"
      description: "The last backup operation failed. Check backup logs for details."

  - alert: BackupMissing
    expr: time() - backup_success_timestamp > 86400
    for: 1h
    labels:
      severity: critical
    annotations:
      summary: "No successful backup in 24 hours"
      description: "No successful backup has been completed in the last 24 hours."

  - alert: BackupDurationHigh
    expr: backup_duration_seconds > 3600
    for: 15m
    labels:
      severity: warning
    annotations:
      summary: "Backup duration too long"
      description: "Backup operation took more than 1 hour to complete."

  - alert: BackupVerificationFailed
    expr: backup_verification_duration_seconds == 0 and backup_last_status == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Backup verification failed"
      description: "The backup verification process failed. Data integrity might be compromised."

  - alert: LowBackupSpace
    expr: backup_available_space_bytes < 10 * 1024 * 1024 * 1024
    for: 30m
    labels:
      severity: warning
    annotations:
      summary: "Low backup storage space"
      description: "Available backup storage space is less than 10GB." 