global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alertmanager@dojopool.com'
  smtp_auth_username: 'alerts@dojopool.com'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'email-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 1h

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'admin@dojopool.com'
        send_resolved: true
        html: '{{ template "email.default.html" . }}'

  - name: 'critical-alerts'
    email_configs:
      - to: 'oncall@dojopool.com'
        send_resolved: true
        html: '{{ template "email.critical.html" . }}'

templates:
  - '/etc/alertmanager/templates/*.tmpl' 