from typing import Any, Dict, List

from flask import Blueprint, jsonify, request
from flask.typing import ResponseReturnValue

from ..auth.utils import login_required
from ..database import db
from ..models.training import TrainingExercise, TrainingSession

def get_training_sessions() -> ResponseReturnValue: ...
def get_training_session(session_id: ...): ...
def create_training_session() -> ResponseReturnValue: ...
def add_exercise(session_id: ...): ...
def start_training_session(session_id: ...): ...
def complete_training_session(session_id: ...): ...
def complete_exercise(exercise_id: ...): ...
