from typing import Any, Dict, List, Optional, Set, Union

from flask import Flask, current_app
from flask_socketio import SocketIO
from werkzeug.wrappers import Response

from ..extensions import socketio
from ..matchmaking.events import MatchEvent, MatchEventType
from .events import handle_match_event, handle_system_event
from .metrics import track_error, track_event

def init_websockets(app: Flask) -> None: ...
def register_event_handlers() -> None: ...
def emit_match_event(event: MatchEvent) -> None: ...
def emit_system_event(event_type: str, data: Dict[str, Any]) -> None: ...
def handle_connection_error(error: Any) -> None: ...
def handle_authentication_error(error: Any) -> None: ...
def handle_disconnection(reason: Optional[str] = None) -> None: ...
