from typing import Any, Dict, List

def get_event_docs(event_name: ...): ...
def get_all_events() -> List[str]: ...
def get_authenticated_events() -> List[str]: ...
def get_event_parameters(event_name: ...): ...
def get_event_response(event_name: ...): ...
