from datetime import datetime
from typing import Any, Dict, List, NoReturn, Optional, Tuple, Union

from flask import Request, Response, current_app, session
from flask.typing import ResponseReturnValue
from flask_socketio import emit, join_room, leave_room
from werkzeug.wrappers import Response as WerkzeugResponse

from .auth import require_permissions
from .constants import ErrorCodes, EventTypes, Permissions
from .decorators import event_handler
from .log_config import logger
from .utils import format_error_response

def handle_connect() -> None: ...
def handle_join_game(data: ...): ...
def handle_leave_game(data: ...): ...
def handle_chat_message(data: ...): ...
def handle_update_score(data: ...): ...
def handle_end_game(data: ...): ...
def handle_join_tournament(data: ...): ...
def handle_leave_tournament(data: ...): ...
def handle_start_tournament(data: ...): ...
def handle_end_tournament(data: ...): ...
