from collections import defaultdict
from datetime import datetime
from typing import Dict

from prometheus_client import Counter, Gauge, Histogram

from ...utils.monitoring import REGISTRY

class MetricsCollector:
    pass

def track_connection(user_id: ...): ...
def track_disconnection(user_id: ...): ...
def start_event(event_id: ...): ...
def end_event(event_id: ...): ...
def track_room_change(room_type: ...): ...
def track_member_change(room_type: ...): ...
def track_error(error_type: ...): ...
def track_rate_limit(event_name: ...): ...
