"""Type stub for room persistence module."""

from pathlib import Path
from typing import Any, Dict, List, Optional, Union

RoomData = Dict[str, Any]

class RoomPersistence:
    data_dir: Path

    def __init__(self, data_dir: Union[str, Path]) -> None: ...
    def _get_room_path(self, room_id: str) -> Path: ...
    async def save_room(self, room_id: str, data: RoomData) -> None: ...
    async def load_room(self, room_id: str) -> Optional[RoomData]: ...
    async def delete_room(self, room_id: str) -> bool: ...
    async def list_rooms(self, room_type: Optional[str] = None) -> List[str]: ...
