import base64
import hashlib
import hmac
import json
import secrets
import uuid
from datetime import datetime
from typing import Any, Dict, List, Optional, Union
from urllib.parse import urlparse

from .constants import ErrorCodes

def get_room_config(room_type: ...): ...
def validate_event_data(event_type: ...): ...
def generate_room_id(prefix: ...): ...
def verify_token(token: ...): ...
def parse_query_string(query_string: ...): ...
def validate_origin(origin: ...): ...
def format_timestamp(dt: ...): ...
def format_bytes(size: ...): ...
def validate_json(data: ...): ...
def generate_nonce(length: ...): ...
