global:
  resolve_timeout: 5m
  slack_api_url: '${SLACK_WEBHOOK_URL}'
  smtp_smarthost: '${SMTP_HOST}:${SMTP_PORT}'
  smtp_from: '${SMTP_FROM}'
  smtp_auth_username: '${SMTP_USER}'
  smtp_auth_password: '${SMTP_PASSWORD}'
  pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'

route:
  group_by: ['alertname', 'severity', 'security_check_type']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'security-slack'
  routes:
    - match:
        severity: critical
      receiver: 'security-pagerduty'
      continue: true
    - match:
        severity: high
      receiver: 'security-slack'
      continue: true
    - match:
        severity: warning
      receiver: 'security-email'

receivers:
  - name: 'security-slack'
    slack_configs:
      - channel: '#dojopool-security'
        send_resolved: true
        icon_emoji: ':shield:'
        title: |-
          [{{ .Status | toUpper }}] Security Alert - {{ .CommonLabels.alertname }}
        text: >-
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
          *Description:* {{ .Annotations.description }}
          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}

  - name: 'security-email'
    email_configs:
      - to: '${SECURITY_EMAIL_TO}'
        send_resolved: true
        headers:
          subject: |-
            [{{ .Status | toUpper }}] Security Alert - {{ .CommonLabels.alertname }}
        html: |-
          {{ range .Alerts }}
            <h3>{{ .Annotations.title }}</h3>
            <p><strong>Description:</strong> {{ .Annotations.description }}</p>
            <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
            <p><strong>Details:</strong></p>
            <ul>
              {{ range .Labels.SortedPairs }}
                <li><strong>{{ .Name }}:</strong> {{ .Value }}</li>
              {{ end }}
            </ul>
          {{ end }}

  - name: 'security-pagerduty'
    pagerduty_configs:
      - routing_key: '${PAGERDUTY_SECURITY_KEY}'
        send_resolved: true
        description: |-
          [{{ .Status | toUpper }}] {{ .CommonLabels.alertname }} - {{ .CommonAnnotations.description }}
        severity: critical
        class: security
        group: '{{ .CommonLabels.security_check_type }}'
        details:
          alert_url: '{{ template "pagerduty.default.alertURL" . }}'
          num_firing: '{{ .Alerts.Firing | len }}'
          num_resolved: '{{ .Alerts.Resolved | len }}'
          alert_details: |-
            {{ range .Alerts -}}
            Alert: {{ .Annotations.title }}
            Description: {{ .Annotations.description }}
            Severity: {{ .Labels.severity }}
            {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'security_check_type'] 