apiVersion: apps/v1
kind: Deployment
metadata:
  name: dojopool-backend
  namespace: dojopool
  labels:
    app: dojopool-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dojopool-backend
  template:
    metadata:
      labels:
        app: dojopool-backend
    spec:
      containers:
        - name: dojopool-backend
          image: dojopool-backend:v1.0.2
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              value: 'production'
            - name: PORT
              value: '3002'
          resources:
            requests:
              memory: '256Mi'
              cpu: '250m'
            limits:
              memory: '512Mi'
              cpu: '500m'
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 5
