apiVersion: apps/v1
kind: Deployment
metadata:
  name: dojopool-frontend
  namespace: dojopool
  labels:
    app: dojopool-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dojopool-frontend
  template:
    metadata:
      labels:
        app: dojopool-frontend
    spec:
      containers:
        - name: dojopool-frontend
          image: dojopool-frontend:v1.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: 'production'
            - name: PORT
              value: '3000'
            - name: NEXT_PUBLIC_API_URL
              value: 'http://dojopool-backend-service:3002'
          resources:
            requests:
              memory: '256Mi'
              cpu: '250m'
            limits:
              memory: '512Mi'
              cpu: '500m'
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
