from datetime import datetime
from typing import Any, Dict, List, NoReturn, Optional, Tuple, Union

from flask import Blueprint, Request, Response, current_app, jsonify, request
from flask.typing import ResponseReturnValue
from flask_login import current_user, login_required
from werkzeug.wrappers import Response as WerkzeugResponse

from ..auth import require_auth
from .manager import GameManager
from .models import GameState

def list_games() -> ResponseReturnValue: ...
def create_game() -> ResponseReturnValue: ...
def get_game(game_id: str) -> ResponseReturnValue: ...
def update_game(game_id: str) -> ResponseReturnValue: ...
def delete_game(game_id: str) -> ResponseReturnValue: ...
def get_game_stats(game_id: str) -> ResponseReturnValue: ...
