import hmac
import secrets
from functools import wraps
from typing import Any, Callable, Dict, List, NoReturn, Optional, Tuple, Union

from flask import Request, Response, abort, current_app, request, session
from flask.typing import ResponseReturnValue
from src.core.exceptions import CSRFError
from werkzeug.wrappers import Response as WerkzeugResponse

def generate_csrf_token() -> str: ...
def verify_csrf_token(token: ...): ...
def csrf_protect(exempt_methods: ...): ...
def csrf_exempt(f: ...): ...
def api_csrf_protect() -> Callable: ...
