import logging
from typing import Any, Dict, List, NoReturn, Optional, Tuple, Union

from flask import Blueprint, Request, Response, current_app, g, jsonify, request
from flask.typing import ResponseReturnValue
from flask_login import current_user, login_required
from werkzeug.wrappers import Response as WerkzeugResponse

from .qr import QRCodeManager

def init_qr_manager(app) -> bool: ...
def generate_table_qr(venue_id: ...): ...
def generate_venue_qr_codes(venue_id: ...): ...
def verify_table_qr() -> ResponseReturnValue: ...
def table_qr_action() -> ResponseReturnValue: ...
def get_table_status_from_qr() -> ResponseReturnValue: ...
