from typing import Any, Dict

from flask import Blueprint, jsonify, request
from flask.typing import ResponseReturnValue

from ..auth.utils import login_required
from ..monitoring.metrics import AlertSeverity, metrics_monitor

def get_game_metrics(game_id: ...): ...
def get_alerts() -> ResponseReturnValue: ...
def acknowledge_alert(alert_id: ...): ...
def record_game_completion(game_id: ...): ...
def record_error(game_id: ...): ...
