import logging
from datetime import datetime
from functools import wraps
from typing import Any, Callable, Dict, List, Optional, Union

import psutil
from flask import Blueprint, Response, current_app, jsonify
from flask.typing import ResponseReturnValue
from werkzeug.wrappers import Response as WerkzeugResponse

from ..auth import is_admin, require_auth

def admin_required(f: ...): ...
def get_metrics() -> ResponseReturnValue: ...
def get_status() -> ResponseReturnValue: ...
def _get_recent_errors() -> List[str]: ...
def _get_recent_warnings() -> List[str]: ...
def _get_network_status() -> str: ...
