apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dojopool-api-hpa
  namespace: production
  annotations:
    description: 'Enhanced auto-scaling for DojoPool API with gaming-specific metrics'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dojopool-api
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Pods
      pods:
        metric:
          name: http_requests_per_second
        target:
          type: AverageValue
          averageValue: 100
    - type: Pods
      pods:
        metric:
          name: http_request_duration_seconds
          selector:
            matchLabels:
              quantile: '0.95'
        target:
          type: AverageValue
          averageValue: 2
    - type: Pods
      pods:
        metric:
          name: websocket_connections_active
        target:
          type: AverageValue
          averageValue: 500
    - type: Pods
      pods:
        metric:
          name: database_connections_active
        target:
          type: AverageValue
          averageValue: 20
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Max
      minReplicas: 3
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dojopool-web-hpa
  namespace: production
  annotations:
    description: 'Enhanced auto-scaling for DojoPool Web with user experience metrics'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dojopool-web
  minReplicas: 2
  maxReplicas: 12
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Pods
      pods:
        metric:
          name: http_requests_per_second
        target:
          type: AverageValue
          averageValue: 50
    - type: Pods
      pods:
        metric:
          name: page_load_duration_seconds
          selector:
            matchLabels:
              quantile: '0.95'
        target:
          type: AverageValue
          averageValue: 3
    - type: Pods
      pods:
        metric:
          name: active_users
        target:
          type: AverageValue
          averageValue: 1000
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 20
          periodSeconds: 60
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Max
      minReplicas: 2
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dojopool-postgresql-hpa
  namespace: production
  annotations:
    description: 'Enhanced auto-scaling for PostgreSQL with database-specific metrics'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: dojopool-postgresql
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Pods
      pods:
        metric:
          name: postgresql_connections
        target:
          type: AverageValue
          averageValue: 100
    - type: Pods
      pods:
        metric:
          name: postgresql_query_duration_seconds
          selector:
            matchLabels:
              quantile: '0.95'
        target:
          type: AverageValue
          averageValue: 1
    - type: Pods
      pods:
        metric:
          name: postgresql_cache_hit_ratio
        target:
          type: AverageValue
          averageValue: 0.95
    - type: Pods
      pods:
        metric:
          name: postgresql_active_queries
        target:
          type: AverageValue
          averageValue: 20
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dojopool-redis-hpa
  namespace: production
  annotations:
    description: 'Enhanced auto-scaling for Redis with caching-specific metrics'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: dojopool-redis
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Pods
      pods:
        metric:
          name: redis_connections
        target:
          type: AverageValue
          averageValue: 1000
    - type: Pods
      pods:
        metric:
          name: redis_hit_rate
        target:
          type: AverageValue
          averageValue: 0.85
    - type: Pods
      pods:
        metric:
          name: redis_memory_fragmentation_ratio
        target:
          type: AverageValue
          averageValue: 1.5
    - type: Pods
      pods:
        metric:
          name: redis_evicted_keys_total
        target:
          type: AverageValue
          averageValue: 10
