apiVersion: v1
kind: ConfigMap
metadata:
  name: texture-ai-config
  namespace: dojopool
  labels:
    app: texture-ai-service
    component: ai-service
data:
  max-resolution: '2048'
  batch-size: '4'
  gpu-enabled: 'false'
  cache-ttl: '3600'
  queue-timeout: '300'
  model-version: 'v1.5'
  processing-timeout: '600'
---
apiVersion: v1
kind: Secret
metadata:
  name: texture-ai-secrets
  namespace: dojopool
  labels:
    app: texture-ai-service
    component: ai-service
type: Opaque
stringData:
  mongodb-uri: 'mongodb://texture-ai-user:CHANGE_ME@mongodb-cluster:27017/dojopool?authSource=admin'
  redis-url: 'redis://redis-cluster:6379/0'
  openai-api-key: 'CHANGE_ME'
  huggingface-token: 'CHANGE_ME'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: texture-ai-models-pvc
  namespace: dojopool
  labels:
    app: texture-ai-service
    component: ai-service
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: texture-ai-service
  namespace: dojopool
  labels:
    app: texture-ai-service
    component: ai-service
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: texture-ai-service-role
  namespace: dojopool
rules:
  - apiGroups: ['']
    resources: ['configmaps', 'secrets']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['']
    resources: ['pods']
    verbs: ['get', 'list', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: texture-ai-service-rolebinding
  namespace: dojopool
subjects:
  - kind: ServiceAccount
    name: texture-ai-service
    namespace: dojopool
roleRef:
  kind: Role
  name: texture-ai-service-role
  apiGroup: rbac.authorization.k8s.io
