global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'application'
    static_configs:
      - targets: ['web:5000']

  - job_name: 'security-metrics'
    metrics_path: '/metrics'
    scrape_interval: 30s
    static_configs:
      - targets: ['security-exporter:9115']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
    metric_relabel_configs:
      - source_labels: [type]
        target_label: security_check_type
      - source_labels: [severity]
        target_label: vulnerability_severity 