global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dojopool_web'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web:80']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'dojopool-staging'

  - job_name: 'dojopool_nginx'
    static_configs:
      - targets: ['web:80']
    metrics_path: '/nginx_status'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'

  - job_name: 'node'
    static_configs:
      - targets: ['web:9100']
    metrics_path: '/metrics'

remote_write:
  - url: "http://prometheus:9090/api/v1/write"

remote_read:
  - url: "http://prometheus:9090/api/v1/read"

storage:
  tsdb:
    path: /prometheus
    retention:
      time: 15d
      size: 5GB 