---
# KICS security scanning configuration
# https://docs.kics.io/latest/configuration-file/

exclude-paths:
  - '**/node_modules/**'
  - '**/venv/**'
  - '**/tests/**'
  - '**/.git/**'
  - '**/dist/**'
  - '**/build/**'
  - '**/coverage/**'

exclude-queries:
  # Exclude specific queries that may generate false positives
  - 'a227ec01-f97a-4084-91a4-47b350c1db54'  # Ignore "Passwords In Configuration Files"
  - '6e2a8c77-9b87-4d93-8c0e-b4c99c1f865c'  # Ignore "Hardcoded Secrets"

exclude-categories: []  # Don't exclude any categories by default

output-formats:
  - 'json'
  - 'sarif'

fail-on:
  - high
  - medium

type:
  - 'Dockerfile'
  - 'CloudFormation'
  - 'Kubernetes'
  - 'OpenAPI'
  - 'Terraform'
  - 'Python'
  - 'JavaScript'
  - 'TypeScript'

secrets-regexes:
  # Custom regex patterns for secret detection
  - '(?i)password\s*[:=]\s*["\']?[^"\'\s]+'
  - '(?i)secret\s*[:=]\s*["\']?[^"\'\s]+'
  - '(?i)key\s*[:=]\s*["\']?[^"\'\s]+'
  - '(?i)token\s*[:=]\s*["\']?[^"\'\s]+'

ignore-on-exit:
  - 'all'  # Don't fail the build on warnings

minimal-ui: false  # Show detailed output

log-file: 'kics-scan.log'

log-level: 'INFO'

timeout: 300  # 5 minutes timeout

profiling: false

ci: true  # Running in CI environment

preview-lines: 3  # Number of lines to show before and after findings

libraries-path: ''  # Use default libraries path 