apiVersion: v1
kind: ConfigMap
metadata:
  name: dojopool-security-policy
  namespace: default
data:
  security-update-policy.json: |
    {
      "security_policy": {
        "vulnerability_classification": {
          "critical": {
            "cvss_score": "9.0-10.0",
            "response_time": "1h",
            "approval_required": false,
            "maintenance_window": "immediate",
            "rollback_time": "15m",
            "testing_required": "smoke_tests_only",
            "communication": ["all_channels", "status_page"]
          },
          "high": {
            "cvss_score": "7.0-8.9",
            "response_time": "4h",
            "approval_required": false,
            "maintenance_window": "security",
            "rollback_time": "30m",
            "testing_required": "regression_tests",
            "communication": ["slack", "email", "status_page"]
          },
          "medium": {
            "cvss_score": "4.0-6.9",
            "response_time": "24h",
            "approval_required": true,
            "maintenance_window": "primary",
            "rollback_time": "1h",
            "testing_required": "full_test_suite",
            "communication": ["slack", "email"]
          },
          "low": {
            "cvss_score": "0.1-3.9",
            "response_time": "72h",
            "approval_required": true,
            "maintenance_window": "primary",
            "rollback_time": "2h",
            "testing_required": "full_test_suite",
            "communication": ["slack"]
          }
        },
        "patch_management": {
          "automated_scanning": {
            "frequency": "daily",
            "tools": ["trivy", "snyk", "owasp_dependency_check"],
            "scope": ["containers", "dependencies", "infrastructure"],
            "reporting": {
              "slack_channel": "#security-scans",
              "dashboard": "security-scanning",
              "alert_threshold": "medium"
            }
          },
          "patch_testing": {
            "environments": ["staging", "canary"],
            "test_types": ["unit", "integration", "performance", "security"],
            "success_criteria": {
              "test_pass_rate": "95%",
              "performance_regression": "< 5%",
              "security_scan_pass": true
            }
          },
          "patch_deployment": {
            "strategy": "canary",
            "traffic_distribution": "10-20-30-40",
            "monitoring_period": "24h",
            "rollback_criteria": {
              "error_rate_increase": "200%",
              "performance_degradation": "20%",
              "user_reports": "10_per_hour"
            }
          }
        },
        "zero_trust_principles": {
          "network_security": {
            "microsegmentation": true,
            "east_west_traffic": "encrypted",
            "service_mesh": "istio",
            "network_policies": "strict"
          },
          "access_control": {
            "principle_of_least_privilege": true,
            "role_based_access": true,
            "just_in_time_access": true,
            "session_management": "strict"
          },
          "data_protection": {
            "encryption_at_rest": true,
            "encryption_in_transit": true,
            "data_classification": true,
            "data_loss_prevention": true
          }
        }
      }
    }

  vulnerability-management.json: |
    {
      "vulnerability_management": {
        "scanning_schedule": {
          "container_images": {
            "frequency": "daily",
            "severity_threshold": "medium",
            "auto_remediation": true
          },
          "dependencies": {
            "frequency": "daily",
            "severity_threshold": "low",
            "auto_remediation": false
          },
          "infrastructure": {
            "frequency": "weekly",
            "severity_threshold": "medium",
            "auto_remediation": true
          },
          "secrets": {
            "frequency": "daily",
            "severity_threshold": "critical",
            "auto_remediation": true
          }
        },
        "response_procedures": {
          "detection": {
            "automated_alerts": true,
            "manual_verification": true,
            "severity_assessment": true,
            "impact_analysis": true
          },
          "assessment": {
            "exploitability_check": true,
            "business_impact": true,
            "remediation_options": true,
            "timeline_estimation": true
          },
          "remediation": {
            "patch_application": true,
            "workaround_implementation": true,
            "monitoring_enhancement": true,
            "communication_plan": true
          },
          "verification": {
            "patch_effectiveness": true,
            "regression_testing": true,
            "monitoring_validation": true,
            "documentation_update": true
          }
        },
        "compliance_requirements": {
          "gdpr": {
            "data_protection": true,
            "privacy_by_design": true,
            "breach_notification": "72h",
            "data_portability": true
          },
          "soc2": {
            "security": true,
            "availability": true,
            "processing_integrity": true,
            "confidentiality": true,
            "privacy": true
          },
          "pci_dss": {
            "cardholder_data": false,
            "payment_processing": true,
            "security_assessment": "annual"
          }
        }
      }
    }
