version: '3.8'

services:
  k6:
    image: grafana/k6:latest
    volumes:
      - ./load-tests:/scripts
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    command: run /scripts/scenarios.js
    networks:
      - dojopool_staging_network
      - loadtest_network

  influxdb:
    image: influxdb:1.8
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    ports:
      - '8086:8086'
    networks:
      - loadtest_network

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - '3001:3000'
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - loadtest_network

networks:
  dojopool_staging_network:
    external: true
  loadtest_network:
    driver: bridge
