import os
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

from flask import Response, current_app
from flask.typing import ResponseReturnValue
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import text
from werkzeug.wrappers import Response as WerkzeugResponse

def init_db(db: ...): ...
def reset_db(db: ...): ...
def backup_db(db: ...): ...
def restore_db(db: ...): ...
def check_connection(db: ...): ...
def get_table_sizes(db: ...): ...
