from typing import Any, Dict, List

from flask import Blueprint, jsonify, request

from ..database import db
from ..exceptions import ValidationError
from ..models.sponsorship import Sponsorship, SponsorshipTier
from ..models.user import User
from ..security import login_required

def get_sponsorship_tiers() -> Dict[str, List[Dict[str, Any]]]: ...
def get_user_sponsorships() -> Dict[str, List[Dict[str, Any]]]: ...
def create_sponsorship() -> Dict[str, Any]: ...
def update_sponsorship(sponsorship_id: ...): ...
def cancel_sponsorship(sponsorship_id: ...): ...
