from datetime import datetime
from typing import Any, Dict, List

from flask import Blueprint, jsonify, request
from flask.typing import ResponseReturnValue
from flask_login import current_user, login_required

from ..auth.utils import admin_required
from ..models import Tournament, Venue, db

def list_tournaments() -> ResponseReturnValue: ...
def get_tournament(tournament_id: ...): ...
def create_tournament() -> ResponseReturnValue: ...
def update_tournament(tournament_id: ...): ...
def delete_tournament(tournament_id: ...): ...
def register_for_tournament(tournament_id: ...): ...
def unregister_from_tournament(tournament_id: ...): ...
def start_tournament(tournament_id: ...): ...
def end_tournament(tournament_id: ...): ...
