groups:
  - name: dojopool.alerts
    rules:
      # API Service Alerts
      - alert: DojoPoolAPIHighErrorRate
        expr: rate(http_requests_total{job="dojopool-api", status=~"5.."}[5m]) / rate(http_requests_total{job="dojopool-api"}[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
          service: api
        annotations:
          summary: 'High error rate on DojoPool API'
          description: 'Error rate is {{ $value | humanize }}% (threshold: 5%)'
          runbook_url: 'https://docs.dojopool.com/runbooks/api-high-error-rate'

      - alert: DojoPoolAPIHighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="dojopool-api"}[5m])) > 2
        for: 5m
        labels:
          severity: warning
          service: api
        annotations:
          summary: 'High latency on DojoPool API'
          description: '95th percentile latency is {{ $value | humanizeDuration }} (threshold: 2s)'
          runbook_url: 'https://docs.dojopool.com/runbooks/api-high-latency'

      - alert: DojoPoolAPIDown
        expr: up{job="dojopool-api"} == 0
        for: 2m
        labels:
          severity: critical
          service: api
        annotations:
          summary: 'DojoPool API is down'
          description: 'DojoPool API has been down for more than 2 minutes'
          runbook_url: 'https://docs.dojopool.com/runbooks/api-down'

      # Web Service Alerts
      - alert: DojoPoolWebHighErrorRate
        expr: rate(nextjs_http_requests_total{job="dojopool-web", status=~"5.."}[5m]) / rate(nextjs_http_requests_total{job="dojopool-web"}[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
          service: web
        annotations:
          summary: 'High error rate on DojoPool Web'
          description: 'Error rate is {{ $value | humanize }}% (threshold: 5%)'
          runbook_url: 'https://docs.dojopool.com/runbooks/web-high-error-rate'

      - alert: DojoPoolWebDown
        expr: up{job="dojopool-web"} == 0
        for: 2m
        labels:
          severity: critical
          service: web
        annotations:
          summary: 'DojoPool Web is down'
          description: 'DojoPool Web has been down for more than 2 minutes'
          runbook_url: 'https://docs.dojopool.com/runbooks/web-down'

      # Database Alerts
      - alert: DojoPoolDatabaseHighConnections
        expr: pg_stat_activity_count{datname="dojopool"} > 80
        for: 5m
        labels:
          severity: warning
          service: database
        annotations:
          summary: 'High database connections'
          description: 'Database has {{ $value }} active connections (threshold: 80)'
          runbook_url: 'https://docs.dojopool.com/runbooks/database-high-connections'

      - alert: DojoPoolDatabaseDown
        expr: pg_up == 0
        for: 2m
        labels:
          severity: critical
          service: database
        annotations:
          summary: 'PostgreSQL database is down'
          description: 'PostgreSQL database has been down for more than 2 minutes'
          runbook_url: 'https://docs.dojopool.com/runbooks/database-down'

      - alert: DojoPoolDatabaseHighLatency
        expr: histogram_quantile(0.95, rate(pg_stat_database_blks_read[5m])) > 1000
        for: 5m
        labels:
          severity: warning
          service: database
        annotations:
          summary: 'High database read latency'
          description: 'Database read operations are slow'
          runbook_url: 'https://docs.dojopool.com/runbooks/database-high-latency'

      # Redis Cache Alerts
      - alert: DojoPoolRedisHighConnections
        expr: redis_connected_clients > 1000
        for: 5m
        labels:
          severity: warning
          service: cache
        annotations:
          summary: 'High Redis connections'
          description: 'Redis has {{ $value }} connected clients (threshold: 1000)'
          runbook_url: 'https://docs.dojopool.com/runbooks/redis-high-connections'

      - alert: DojoPoolRedisDown
        expr: redis_up == 0
        for: 2m
        labels:
          severity: critical
          service: cache
        annotations:
          summary: 'Redis cache is down'
          description: 'Redis cache has been down for more than 2 minutes'
          runbook_url: 'https://docs.dojopool.com/runbooks/redis-down'

      - alert: DojoPoolRedisHighMemoryUsage
        expr: redis_used_memory_bytes / redis_total_system_memory_bytes > 0.8
        for: 5m
        labels:
          severity: warning
          service: cache
        annotations:
          summary: 'High Redis memory usage'
          description: 'Redis memory usage is {{ $value | humanize }}% (threshold: 80%)'
          runbook_url: 'https://docs.dojopool.com/runbooks/redis-high-memory'

      # Infrastructure Alerts
      - alert: DojoPoolHighCPUUsage
        expr: rate(container_cpu_usage_seconds_total{pod=~"dojopool-.*"}[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
          service: infrastructure
        annotations:
          summary: 'High CPU usage on DojoPool pods'
          description: 'Pod {{ $labels.pod }} has high CPU usage: {{ $value | humanize }} cores'
          runbook_url: 'https://docs.dojopool.com/runbooks/high-cpu-usage'

      - alert: DojoPoolHighMemoryUsage
        expr: container_memory_usage_bytes{pod=~"dojopool-.*"} / container_spec_memory_limit_bytes > 0.85
        for: 5m
        labels:
          severity: warning
          service: infrastructure
        annotations:
          summary: 'High memory usage on DojoPool pods'
          description: 'Pod {{ $labels.pod }} memory usage is {{ $value | humanize }}% (threshold: 85%)'
          runbook_url: 'https://docs.dojopool.com/runbooks/high-memory-usage'

      - alert: DojoPoolPodRestarts
        expr: increase(kube_pod_container_status_restarts_total{pod=~"dojopool-.*"}[10m]) > 0
        for: 1m
        labels:
          severity: warning
          service: infrastructure
        annotations:
          summary: 'DojoPool pod restarted'
          description: 'Pod {{ $labels.pod }} restarted {{ $value }} times in the last 10 minutes'
          runbook_url: 'https://docs.dojopool.com/runbooks/pod-restarts'

      # Business Logic Alerts
      - alert: DojoPoolLowActiveUsers
        expr: dojopool_active_users < 10
        for: 30m
        labels:
          severity: info
          service: business
        annotations:
          summary: 'Low active users'
          description: 'Only {{ $value }} active users in the last 30 minutes (threshold: 10)'
          runbook_url: 'https://docs.dojopool.com/runbooks/low-active-users'

      - alert: DojoPoolHighWebSocketConnections
        expr: dojopool_websocket_connections > 10000
        for: 5m
        labels:
          severity: info
          service: business
        annotations:
          summary: 'High WebSocket connections'
          description: 'WebSocket connections: {{ $value }} (threshold: 10000)'
          runbook_url: 'https://docs.dojopool.com/runbooks/high-websocket-connections'

      - alert: DojoPoolDatabaseSlowQueries
        expr: rate(dojopool_slow_queries_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
          service: database
        annotations:
          summary: 'Slow database queries detected'
          description: 'Slow queries per second: {{ $value }} (threshold: 10)'
          runbook_url: 'https://docs.dojopool.com/runbooks/slow-queries'

      # Security Alerts
      - alert: DojoPoolHighFailedLogins
        expr: rate(dojopool_failed_login_attempts[5m]) > 5
        for: 5m
        labels:
          severity: warning
          service: security
        annotations:
          summary: 'High failed login attempts'
          description: 'Failed login rate: {{ $value }}/second (threshold: 5/5min)'
          runbook_url: 'https://docs.dojopool.com/runbooks/high-failed-logins'

      - alert: DojoPoolSuspiciousLocationRequests
        expr: rate(dojopool_suspicious_location_requests[5m]) > 10
        for: 5m
        labels:
          severity: warning
          service: security
        annotations:
          summary: 'Suspicious location requests detected'
          description: 'Suspicious requests: {{ $value }}/second (threshold: 10/5min)'
          runbook_url: 'https://docs.dojopool.com/runbooks/suspicious-location-requests'
