from datetime import datetime
from functools import wraps
from io import BytesIO
from typing import Any, Callable, Dict, List, Optional, TypeVar, cast

from flask import Blueprint, jsonify, request, send_file
from flask.typing import ResponseReturnValue
from flask_login import current_user, login_required

from ..auth import require_permissions
from .models import PoolTable, Venue, VenueStaff, venue_manager
from .qr import QRCodeManager, qr_manager
from .qr_alerts import AlertSeverity, qr_alerts
from .qr_export import qr_export
from .qr_stats import qr_stats
from .rate_limit import rate_limit

def validate_venue_access(f: ...): ...
def list_venues() -> ResponseReturnValue: ...
def get_venue(venue_id: ...): ...
def create_venue() -> ResponseReturnValue: ...
def update_venue(venue_id: ...): ...
def add_table(venue_id: ...): ...
def update_table(venue_id: ...): ...
def add_staff(venue_id: ...): ...
def get_venue_qr(venue_id: ...): ...
def get_qr_stats(venue_id: ...): ...
def export_qr_codes(venue_id: ...): ...
def get_qr_alerts(venue_id: ...): ...
