name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack (Yarn v4)
        run: corepack enable

      - name: Install dependencies (Yarn)
        run: yarn install --immutable

      - name: Type check (monorepo)
        run: yarn type-check

      - name: Lint (strict)
        run: yarn lint:strict

      - name: Unit tests with coverage (80% threshold)
        run: yarn test:unit:coverage

      - name: Integration tests with coverage (80% threshold)
        run: yarn test:int:coverage
name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  env-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install deps (root)
        run: yarn install --frozen-lockfile
      - name: Install deps (api)
        run: yarn workspace @dojopool/api install --frozen-lockfile
      - name: Validate environment (strict)
        run: yarn run env:check:strict

  lint-and-types:
    runs-on: ubuntu-latest
    needs: env-validate
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install deps (root)
        run: yarn install --frozen-lockfile
      - name: Install deps (api)
        run: yarn workspace @dojopool/api install --frozen-lockfile
      - name: Lint
        run: yarn run lint
      - name: Type check (web and api)
        run: yarn run type-check

  tests:
    runs-on: ubuntu-latest
    needs: lint-and-types
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install deps (root)
        run: yarn install --frozen-lockfile
      - name: Install deps (api)
        run: yarn workspace @dojopool/api install --frozen-lockfile
      - name: Run tests (CI)
        run: yarn run test:ci

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install deps (root)
        run: yarn install --frozen-lockfile
      - name: Install deps (api)
        run: yarn workspace @dojopool/api install --frozen-lockfile
      - name: Build backend
        run: yarn run build:backend
      - name: Build frontend
        run: yarn run build
