name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  env-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install deps (root)
        run: yarn install --frozen-lockfile
      - name: Install deps (api)
        run: yarn workspace @dojopool/api install --frozen-lockfile
      - name: Validate environment (strict)
        run: yarn run env:check:strict

  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install deps (root)
        run: yarn install --frozen-lockfile
      - name: Install deps (api)
        run: yarn workspace @dojopool/api install --frozen-lockfile
      - name: Security audit
        run: yarn audit --level moderate
      - name: Check for known vulnerabilities
        run: yarn audit --audit-level moderate --json > audit-results.json || true
      - name: Upload audit results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-audit-results
          path: audit-results.json

  lint-and-types:
    runs-on: ubuntu-latest
    needs: [env-validate, security-audit]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install deps (root)
        run: yarn install --frozen-lockfile
      - name: Install deps (api)
        run: yarn workspace @dojopool/api install --frozen-lockfile
      - name: Lint
        run: yarn run lint
      - name: Type check (web and api)
        run: yarn run type-check

  tests:
    runs-on: ubuntu-latest
    needs: lint-and-types
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install deps (root)
        run: yarn install --frozen-lockfile
      - name: Install deps (api)
        run: yarn workspace @dojopool/api install --frozen-lockfile
      - name: Run tests (CI)
        run: yarn run test:ci

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install deps (root)
        run: yarn install --frozen-lockfile
      - name: Install deps (api)
        run: yarn workspace @dojopool/api install --frozen-lockfile
      - name: Build backend
        run: yarn run build:backend
      - name: Build frontend
        run: yarn run build
