on:name: Common Checks
on:
  push:
    paths:
    - src/**
    - package.json
    - package-lock.json
    - .eslintrc.js
    - .prettierrc
    - tsconfig.json
    - tests/**
    - cypress/**
    branches:
    - main
    - develop
  pull_request:
    paths:
    - src/**
    - package.json
    - package-lock.json
    - .eslintrc.js
    - .prettierrc
    - tsconfig.json
    - tests/**
    - cypress/**
    branches:
    - main
    - develop
permissions:
  contents: read
  actions: write
  checks: write
  pull-requests: write
  security-events: write
  issues: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
      continue-on-error: true
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: npm
      continue-on-error: true
    - name: Cache dependencies
      uses: actions/cache@v3
      id: npm-cache
      with:
        path: '~/.npm

          node_modules

          '
        key: ${{{ runner.os }}-node-${{{ hashFiles('**/package-lock.json') }}
        restore-keys: '${{{ runner.os }}-node-

          '
      continue-on-error: true
    - name: Install dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true''
      run: "for i in {1..3}}; do\n  echo \"Attempt $i of 3\"\n  if npm ci; then\n\
        \    exit 0\n  fi\n  echo \"npm ci failed, retrying...\"\n  sleep 5\ndone\n\
        exit 1\n"
      continue-on-error: true
    - name: Run linting
      id: lint
      run: npm run lint
      continue-on-error: true
    - name: Run formatting check
      id: format
      run: npm run format:check
      continue-on-error: true
    - name: Run type checking
      id: types
      run: npm run type-check
      continue-on-error: true
    - name: Upload lint results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: lint-results
        path: 'reports/eslint/

          reports/prettier/

          reports/tsc/

          '
        retention-days: 30
        if-no-files-found: warn
      continue-on-error: true
    - name: Report status
      if: always()
      run: "if [[ \"${{{ steps.lint.outcome }}\" == \"failure\" || \"${{{ steps.format.outcome\
        \ }}\" == \"failure\" || \"${{{ steps.types.outcome }}\" == \"failure\"\
        \ ]]; then\n  echo \"::error::One or more checks failed\"\n  echo \"::group::Lint\
        \ Results\"\n  cat reports/eslint/results.json || true\n  echo \"::endgroup::\"\
        \n  echo \"::group::Format Results\"\n  cat reports/prettier/results.json\
        \ || true\n  echo \"::endgroup::\"\n  echo \"::group::Type Check Results\"\
        \n  cat reports/tsc/results.json || true\n  echo \"::endgroup::\"\n  exit\
        \ 1\nfi\n"
      continue-on-error: true
