name: Common Workflow Configuration

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '18'
      cache-dependency-path:
        required: false
        type: string
        default: 'package-lock.json'
      working-directory:
        required: false
        type: string
        default: '.'
    outputs:
      cache-hit:
        description: "Whether there was a cache hit for dependencies"
        value: ${{ jobs.setup.outputs.cache-hit }}

permissions:
  contents: read
  pull-requests: write
  checks: write
  actions: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.npm-cache.outputs.cache-hit }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: ${{ inputs.cache-dependency-path }}
      
      - name: Cache dependencies
        id: npm-cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            ~/.npm
            .next/cache
          key: ${{ runner.os }}-npm-${{ hashFiles(inputs.cache-dependency-path) }}
          restore-keys: |
            ${{ runner.os }}-npm-
      
      - name: Install Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          npm ci
          npm audit fix

  validate:
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: ${{ inputs.cache-dependency-path }}
      
      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            ~/.npm
            .next/cache
          key: ${{ runner.os }}-npm-${{ hashFiles(inputs.cache-dependency-path) }}
      
      - name: Run Type Check
        id: typecheck
        run: npm run type-check
        continue-on-error: true
      
      - name: Run Tests
        id: test
        run: npm test -- --coverage
        continue-on-error: true
      
      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        if: always() && steps.test.outcome == 'success'
        with:
          name: coverage-report
          path: coverage/
          retention-days: 14
      
      - name: Check Results
        if: always()
        run: |
          if [[ "${{ steps.typecheck.outcome }}" == "failure" ]] || \
             [[ "${{ steps.test.outcome }}" == "failure" ]]; then
            echo "One or more validation steps failed"
            exit 1
          fi
