name: Deploy to Firebase
on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'
      - '**.txt'
    branches:
      - main
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Enable Corepack
        run: corepack enable
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Build
        run: cd apps/web && yarn build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY || 'test-key'}}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{secrets.FIREBASE_AUTH_DOMAIN || 'test-domain'}}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID || 'test-project'}}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{secrets.FIREBASE_STORAGE_BUCKET || 'test-bucket'}}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{secrets.FIREBASE_MESSAGING_SENDER_ID || 'test-sender'}}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{secrets.FIREBASE_APP_ID || 'test-app'}}
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{secrets.FIREBASE_MEASUREMENT_ID || 'test-measurement'}}
          NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{secrets.RECAPTCHA_SITE_KEY || 'test-recaptcha'}}
      - name: Deploy to Firebase
        run: |
          if [ "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" != "" ]; then
            echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > firebase-service-account.json
            export GOOGLE_APPLICATION_CREDENTIALS=firebase-service-account.json
            firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID || 'test-project' }}
          else
            echo "Firebase service account not configured, skipping deployment"
          fi
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
        continue-on-error: true
