name: Firebase Deployment

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/firebase-deploy.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'firebase.json'
      - '.firebaserc'
    branches:
      - main
      - staging

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NODE_ENV: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
          NEXT_PUBLIC_API_URL: ${{ github.ref == 'refs/heads/main' && secrets.PROD_API_URL || secrets.STAGING_API_URL }}

      - name: Deploy to Firebase
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0.7.1
        with:
          repoToken: ${{secrets.GITHUB_TOKEN}}
          firebaseServiceAccount: ${{secrets.FIREBASE_SERVICE_ACCOUNT}}
          channelId: ${{ github.ref == 'refs/heads/main' && 'live' || 'staging' }}
          projectId: ${{secrets.FIREBASE_PROJECT_ID}}

      - name: Verify deployment
        run: |
          sleep 30
          curl -sSf ${{steps.deploy.outputs.url}} > /dev/null || exit 1
          curl -sSf "${{steps.deploy.outputs.url}}/__/firebase/init.json" > /dev/null || exit 1

      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
          SLACK_CHANNEL: deployments
          SLACK_COLOR: ${{job.status == 'success' && 'good' || 'danger'}}
          SLACK_TITLE: Firebase Deployment ${{job.status == 'success' && 'Successful' || 'Failed'}}
          SLACK_MESSAGE: |
            Environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Staging' }}
            Branch: ${{github.ref_name}}
            Commit: ${{github.sha}}
            URL: ${{steps.deploy.outputs.url}}
