name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read
  pull-requests: write
  checks: write
  actions: write

jobs:
  common:
    uses: ./.github/workflows/common.yml
    with:
      node-version: '18'

  build:
    needs: common
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: success()
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Build Project
        run: npm run build
        
      - name: Cache Build
        uses: actions/cache@v4
        with:
          path: .next
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
