name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'

permissions:
  contents: read
  pull-requests: write
  checks: write
  actions: write
  security-events: write
  deployments: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.node-version.outputs.version }}
    steps:
      - name: Determine Node.js version
        id: node-version
        run: |
          echo "version=18" >> $GITHUB_OUTPUT

  security:
    name: Security Scan
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.setup.outputs.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          npm audit fix || true
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
      
      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        continue-on-error: true
        with:
          sarif_file: 'trivy-results.sarif'

  lint:
    name: Lint & Format
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.setup.outputs.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          npm install -g eslint prettier
      
      - name: Cache eslint results
        uses: actions/cache@v4
        with:
          path: |
            .eslintcache
            .prettierignore
          key: ${{ runner.os }}-eslint-${{ hashFiles('.eslintrc.json') }}
      
      - name: Run ESLint
        continue-on-error: true
        run: |
          npm run lint || true
          eslint . --fix || true
      
      - name: Run Prettier
        continue-on-error: true
        run: |
          npm run format || true
          prettier --write . || true

  test:
    name: Test
    needs: [setup, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.setup.outputs.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          npm install -g jest
      
      - name: Cache Jest
        uses: actions/cache@v4
        with:
          path: |
            node_modules/.cache/jest
          key: ${{ runner.os }}-jest-${{ hashFiles('package-lock.json') }}
      
      - name: Run tests
        continue-on-error: true
        run: |
          npm test -- --coverage || true
      
      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
          retention-days: 14

  build:
    name: Build
    needs: [setup, security, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.setup.outputs.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          npm install -g next
      
      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-
      
      - name: Build
        run: |
          npm run build || (
            echo "Build failed, retrying with clean cache..."
            rm -rf .next
            npm run build
          )
      
      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: .next
          retention-days: 14

  deploy-staging:
    name: Deploy to Staging
    if: github.ref == 'refs/heads/develop'
    needs: [setup, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .next
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}
      
      - name: Deploy to staging
        env:
          STAGE: staging
          DEPLOY_URL: ${{ vars.STAGING_URL || 'https://staging.dojopool.com' }}
        run: |
          echo "Deploying to staging environment at $DEPLOY_URL"
          # Add deployment commands here

  deploy-production:
    name: Deploy to Production
    if: github.ref == 'refs/heads/main'
    needs: [setup, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .next
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}
      
      - name: Deploy to production
        env:
          STAGE: production
          DEPLOY_URL: ${{ vars.PRODUCTION_URL || 'https://dojopool.com' }}
        run: |
          echo "Deploying to production environment at $DEPLOY_URL"
          # Add deployment commands here
