name: CI Check

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Basic Check
        run: |
          echo "Running basic check"
          echo "Current directory: $PWD"
          echo "GitHub workspace: $GITHUB_WORKSPACE"
          echo "Check completed"
