name: Nginx Tests

on:
  push:
    paths:
      - 'nginx/**'
      - '.github/workflows/nginx-test.yml'
      - 'docker/nginx/**'
    branches:
      - main
      - develop
  pull_request:
    paths:
      - 'nginx/**'
      - '.github/workflows/nginx-test.yml'
      - 'docker/nginx/**'
    branches:
      - main
      - develop

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  nginx-test:
    name: Test Nginx Configuration
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: buildx-nginx-${{runner.os}}-${{github.sha}}
          restore-keys: |
            buildx-nginx-${{runner.os}}-

      - name: Build Nginx image
        uses: docker/build-push-action@v4
        with:
          context: ./nginx
          load: true
          tags: dojopool/nginx:test
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Test Nginx configuration
        run: |
          docker run --rm dojopool/nginx:test nginx -t

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: nginx-test-results
          path: nginx/logs/
          retention-days: 30
