name: Performance Monitoring

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/performance.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'lighthouse/**'
    branches:
      - main
      - develop
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  lighthouse:
    name: Lighthouse Audit
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_API_URL: ${{secrets.PROD_API_URL}}

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            ${{steps.deploy.outputs.url}}
            ${{steps.deploy.outputs.url}}/auth/signin
            ${{steps.deploy.outputs.url}}/dashboard
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: ./.github/lighthouse/config.json

      - name: Upload Lighthouse results
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-results
          path: .lighthouseci/
          retention-days: 30

  k6:
    name: K6 Load Test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: Run k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: k6/load-test.js
          flags: --vus 10 --duration 30s

      - name: Upload k6 results
        uses: actions/upload-artifact@v2
        with:
          name: k6-results
          path: k6/results/
          retention-days: 30

  bundle-analysis:
    name: Bundle Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build with source maps
        run: GENERATE_SOURCEMAP=true npm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_API_URL: ${{secrets.PROD_API_URL}}

      - name: Analyze bundle
        run: npx source-map-explorer 'build/static/js/*.js'

      - name: Upload bundle analysis
        uses: actions/upload-artifact@v2
        with:
          name: bundle-analysis
          path: bundle-analysis.html
          retention-days: 30
