name: Performance Tests

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/performance-tests.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'cypress/integration/performance/**'
    branches:
      - main
      - develop
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/performance-tests.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'cypress/integration/performance/**'
    branches:
      - main
      - develop

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  performance:
    name: Run Performance Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
          cache: npm

      - name: Cache Cypress binary
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress-${{runner.os}}-${{hashFiles('**/package-lock.json')}}
          restore-keys: |
            cypress-${{runner.os}}-

      - name: Install dependencies
        run: npm ci

      - name: Run performance tests
        run: |
          npm run build
          npm run start & npx wait-on http://localhost:3000
          npm run cypress:run -- --spec "cypress/integration/performance/**/*.spec.ts"
        env:
          CYPRESS_PERFORMANCE_TEST: true

      - name: Upload performance results
        uses: actions/upload-artifact@v2
        with:
          name: performance-results
          path: cypress/results/performance/
          retention-days: 30
