name: Performance Testing

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *" # Daily at midnight UTC

jobs:
  performance:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run performance tests
        run: npm run test:perf

      - name: Check performance budgets
        run: npm run perf:check

      - name: Upload performance results
        uses: actions/upload-artifact@v3
        with:
          name: performance-results
          path: performance-results/

      - name: Check for regressions
        run: npm run perf:regression

      - name: Report status
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const results = JSON.parse(fs.readFileSync('performance-results/summary.json', 'utf8'));

            const formatMetric = (value) => {
              return value.toFixed(2);
            };

            let summary = '## Performance Test Results\n\n';
            summary += '| Metric | Value | Budget | Status |\n';
            summary += '|--------|--------|--------|--------|\n';

            for (const metric of results.metrics) {
              const status = metric.value <= metric.budget ? '✅' : '❌';
              summary += `| ${metric.name} | ${formatMetric(metric.value)}ms | ${formatMetric(metric.budget)}ms | ${status} |\n`;
            }

            if (results.regressions.length > 0) {
              summary += '\n### Performance Regressions Detected\n\n';
              for (const regression of results.regressions) {
                summary += `- ${regression.metric}: ${formatMetric(regression.difference)}ms slower\n`;
              }
            }

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: summary
            });
