name: PR AI Description

on:
  pull_request:
    types: [opened, edited, synchronize, labeled]

jobs:
  generate-pr-description:
    if: contains(github.event.pull_request.labels.*.name, 'ai-describe') || github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Generate PR description (AI)
        if: ${{ secrets.OPENAI_API_KEY != '' }}
        id: generate
        run: |
          DESC=$(node scripts/ai/generate-pr-description.js)
          echo "DESC<<EOF" >> $GITHUB_OUTPUT
          echo "$DESC" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: Update PR body
        if: steps.generate.outputs.DESC != ''
        uses: actions-ecosystem/action-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          comment-id: ${{ github.event.pull_request.number }}
          body: ${{ steps.generate.outputs.DESC }}