name: Security Scan and Updates

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run yarn audit
        run: yarn audit --level moderate || echo "Security audit completed with warnings"

      - name: Run CodeQL Analysis
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Update dependencies (if vulnerabilities found)
        run: |
          # Only update if there are vulnerabilities
          if yarn audit --level moderate --json | grep -q '"vulnerabilities"'; then
            echo "Vulnerabilities found, updating dependencies..."
            yarn upgrade
            yarn audit --level moderate || echo "Security audit completed with warnings"
          else
            echo "No vulnerabilities found, skipping dependency updates"
          fi

      - name: Create Pull Request (if updates made)
        if: github.event_name == 'schedule'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'chore: update dependencies and fix security vulnerabilities'
          title: 'Security: Update dependencies and fix vulnerabilities'
          body: |
            Automated security update

            - Updated dependencies to latest secure versions
            - Fixed security vulnerabilities
            - Run yarn audit

            Please review the changes and merge if tests pass.
          branch: security-updates
          delete-branch: true
          labels: security,dependencies

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
