name: Security Scan and Updates

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run npm audit
        run: npm audit

      - name: Run CodeQL Analysis
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Update dependencies
        run: |
          npm install next@latest axios@latest jspdf@latest canvg@latest @babel/runtime@latest @babel/helpers@latest dompurify@latest cross-spawn@latest http-cache-semantics@latest semver-regex@latest got@latest cookie@latest --legacy-peer-deps
          npm audit fix --force --legacy-peer-deps
          npm install --legacy-peer-deps

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: update dependencies and fix security vulnerabilities"
          title: "Security: Update dependencies and fix vulnerabilities"
          body: |
            Automated security update

            - Updated dependencies to latest secure versions
            - Fixed security vulnerabilities
            - Run npm audit fix

            Please review the changes and merge if tests pass.
          branch: security-updates
          delete-branch: true
          labels: security,dependencies

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
