name: Tests
on:
  push:
    paths:
      - 'src/core/matchmaking/**'
      - 'test-requirements.txt'
      - '.github/workflows/tests.yml'
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'
      - '**.txt'
    branches:
      - main
  pull_request:
    paths:
      - 'src/core/matchmaking/**'
      - 'test-requirements.txt'
      - '.github/workflows/tests.yml'
    branches:
      - main

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      
      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{runner.os}}-py${{matrix.python-version}}-${{hashFiles('**/test-requirements.txt')}}
          restore-keys: |
            pip-${{runner.os}}-py${{matrix.python-version}}-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt
      
      - name: Run tests
        run: |
          python -m pytest src/core/matchmaking/tests/run_tests.py -v --cov=src/core/matchmaking --cov-report=xml
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
