name: Tests

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/tests.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'jest.config.js'
      - 'coverage/**'
    branches:
      - main
      - develop
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/tests.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'jest.config.js'
      - 'coverage/**'
    branches:
      - main
      - develop

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests (${{ matrix.os }}, Node ${{ matrix.node-version }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ matrix.os }}-${{ matrix.node-version }}-
            npm-${{ matrix.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        id: test
        run: |
          npm test -- --coverage --coverageThreshold='{"global":{"branches":"80","functions":"80","lines":"80","statements":"80"}}'
        continue-on-error: true

      - name: Check test status
        if: steps.test.outcome == 'failure'
        run: |
          echo "Tests failed or coverage thresholds not met"
          exit 1

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.os }}-node-${{ matrix.node-version }}
          path: |
            coverage/
            junit.xml
          retention-days: 30

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: ./coverage/lcov.info
          flags: unittests,${{ matrix.os }},node-${{ matrix.node-version }}
          name: codecov-${{ matrix.os }}-node-${{ matrix.node-version }}
          fail_ci_if_error: true
          verbose: true

      - name: Generate coverage report
        if: always()
        run: |
          npm install -g jest-html-reporter
          jest --coverage --reporters=jest-html-reporter

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-${{ matrix.os }}-node-${{ matrix.node-version }}
          path: test-report.html
          retention-days: 30

  notify:
    name: Notify Results
    needs: test
    runs-on: ubuntu-latest
    if: always()
    timeout-minutes: 10

    steps:
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
          SLACK_CHANNEL: testing
          SLACK_COLOR: ${{ needs.test.result == 'success' && 'good' || 'danger' }}
          SLACK_TITLE: Test Results ${{ needs.test.result == 'success' && 'Passed ✅' || 'Failed ❌' }}
          SLACK_MESSAGE: |
            *Branch:* ${{ github.ref_name }}
            *Commit:* ${{ github.sha }}
            *Coverage Reports:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            *Status:* ${{ needs.test.result }}
            
            *Matrix Results:*
            - Ubuntu + Node 18: ${{ needs.test.result }}
            - Ubuntu + Node 20: ${{ needs.test.result }}
            - Windows + Node 18: ${{ needs.test.result }}
            - Windows + Node 20: ${{ needs.test.result }}
            - macOS + Node 18: ${{ needs.test.result }}
            - macOS + Node 20: ${{ needs.test.result }}
