name: Tests

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/tests.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'jest.config.js'
    branches:
      - main
      - develop
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/tests.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'jest.config.js'
    branches:
      - main
      - develop

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test -- --coverage

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: coverage/
          retention-days: 30

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
