name: Type Check
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  typecheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python-version}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy types-python-dateutil types-requests types-PyYAML fastapi-utils pytest-asyncio
        pip install -r requirements.txt
    - name: Run mypy
      run: |
        mypy src/dojopool/core/ranking/
        mypy src/dojopool/tests/core/ranking/
    - name: Run tests with type checking
      run: |
        pytest src/dojopool/tests/core/ranking/ --mypy -v
    - name: Cache mypy
      uses: actions/cache@v4
      with:
        path: .mypy_cache
        key: mypy-${{runner.os}}-${{matrix.python-version}}-${{hashFiles('**/requirements.txt')}}
        restore-keys: |
          mypy-${{runner.os}}-${{matrix.python-version}}-
        enableCrossOsArchive: true
        fail-on-cache-miss: false
        lookup-only: false
