name: Type Check

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/type-check.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
    branches:
      - main
      - develop
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/type-check.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
    branches:
      - main
      - develop

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run: npm run type-check

      - name: Upload type check results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: type-check-results
          path: reports/tsc/
          retention-days: 30
