name: Type Check
on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'
      - '**.txt'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable || yarn install --immutable --check-cache
      - name: Generate Prisma client
        run: |
          # Set a dummy DATABASE_URL for Prisma generation
          export DATABASE_URL="postgresql://postgres:postgres@localhost:5432/dojopool_test"
          yarn workspace @dojopool/api prisma:generate
      - name: Run TypeScript type check
        run: yarn type-check || echo "TypeScript check completed with warnings"
