from datetime import datetime, timedelta
from typing import Dict, List, Optional, Set, Tuple

from ...models.user import User
from ...models.venue import Venue
from ..config.matchmaking import LOCATION_SETTINGS, TIME_SETTINGS

def get_mutual_friends(user1: ...): ...
def check_scheduling_conflicts(user1: ...): ...
def validate_preferences(preferences: ...): ...
def format_wait_time(seconds: ...): ...
